name: flutter_mobile_platform_showcase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0-103.1.beta

dependencies:
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
